name: Xpense
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^9.0.0
  objectbox: ^4.0.3
  objectbox_flutter_libs: any
  path: ^1.9.0
  path_provider: ^2.1.5
  flutter_rating_bar: ^4.0.1
  faker: ^2.2.0
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  objectbox_generator: any

flutter:
  uses-material-design: true

  assets:
    - assets/atocodes.jpg

objectbox:
  output_dir: database/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/app_ico/ico.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  